config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list_id,
    message: "La pelicula ya se encuentra registrada" }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_one_attached :photo
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmark = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to @list
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to lists_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @photo = @list.photo
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
<ul>
  <% @bookmarks.each do |bookmark| %>
    <li><%= bookmark.name %></li>
  <% end %>
</ul>

app/views/bookmarks/new.html.erb
<h1>Comment your favorite movie!</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

<%= link_to "< back to lists" , lists_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<!-- app/views/list/index.html.erb -->
<div class="banner b-index d-flex align-items-center">
  <div class="container">
    <h1>Movies watch-list!</h1>
    <p>Watch the best movies here</p>
  </div>
</div>
<div class="container">
  <div class="lists d-flex justify-content-between mt-4 p-3">
    <div>
      <strong>My Lists</strong>
    </div>
    <div class="">
      <%= link_to new_list_path do %>
        <button class="btn btn-dark">Add a new list</button>
      <% end %>
    </div>
  </div>
  <div class="d-flex">
    <% @lists.each do |list| %>
      <div class="card ms-3">
        <%= link_to list_path(list) do%>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= url_for list.photo %>')">
            <%= list.name %>
          </div>
        <% end %>
        <%= link_to "Delete",
          list_path(list),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
        %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<!-- app/views/list/new.html.erb -->
<h1>Create a New List!</h1>
<%= simple_form_for(@list) do |f| %>
  <%= f.text_field :name, label: "name of list"%>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

<%= link_to "Back to My Lists", lists_path%>

app/views/lists/show.html.erb
<!-- app/views/list/show.html.erb -->
<div class="banner b-show d-flex align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= url_for @list.photo %>')">
  <div class="container">
    <h1><%= @list.name %></h1>
    <p>My favorites <%= @list.name %> movies</p>
  </div>
</div>
<h2><%= @list.name %></h2>
<% @list.movies.each do |movie| %>
  <%= image_tag movie.poster_url, width: "100px" %>
  <%= movie.title %>
  <div>
    <% movie.bookmarks.each do |element| %>
      <%= element.comment %>
    <% end %>
  </div>
<% end %>
<%= link_to "< back", lists_path%>
| <%= link_to " Add review", new_list_bookmark_path(@list)%>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://th.bing.com/th/id/OIP.HUvoZFQrXAp6s2rO_kjSeQHaHa?rs=1&pid=ImgDetMain" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://cdn-icons-png.flaticon.com/512/5189/5189320.png" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>